### ISSUE TITLE
中文乱码

### ISSUE THREAD

**Issue by automano** [mli/autocut#1]
老师，中文识别出来都是乱码可能是什么原因呢？

![image](https://user-images.githubusercontent.com/17286982/200301949-ba2902bd-ac87-476b-b7a3-f60356b19c7b.png)
![image](https://user-images.githubusercontent.com/17286982/200302019-2585d2d5-92b4-4218-b9cc-da22462fd674.png)

**Comment by automano** [comment]
其他小伙伴有遇到的吗？
另外附上python和pytorch版本，GPU是1080Ti
![image](https://user-images.githubusercontent.com/17286982/200303914-3dbb8676-8f2b-4f9f-a4fa-5efd45178920.png)

**Comment by wk-mike** [comment]
我是正常的。你改一下显示字符的型号，在vs code右下角有个UTF-8，点一下，改动一下

**Comment by yishibakaien** [comment]
我碰到了和你一样的问题，直接运行 `autocut -t ./videos/xxx.mp4` 使用的是 CPU 进行处理，如何使用GPU呢？

**Comment by yishibakaien** [comment]
> 我是正常的。你改一下显示字符的型号，在vs code右下角有个UTF-8，点一下，改动一下

我的右下角是 UTF-8，不能正常显示，需要怎么改？

**Comment by wk-mike** [comment]
@yishibakaien  你把这个文件发到附件里面试试

**Comment by yishibakaien** [comment]
> @yishibakaien 你把这个文件发到附件里面试试

[2022-11-07.md](https://github.com/mli/autocut/files/9952468/2022-11-07.md)
你看看这个 `.md` 文件，`.srt` 文件有同样的问题，但是 github不支持上传

**Comment by yishibakaien** [comment]
![image](https://user-images.githubusercontent.com/17696228/200333697-5df24fd5-b454-4941-ba2e-9921c98c15ac.png)
![image](https://user-images.githubusercontent.com/17696228/200333750-87fdcfb5-8f40-4d2b-916f-572fd928fe7b.png)

@wk-mike  这是截图

**Comment by wk-mike** [comment]
@yishibakaien  我打开也是乱码，不知道是什么原因，改字符型号似乎没有用

**Comment by yishibakaien** [comment]
我临时解决了这个问题，右下角修改编码集为 GB2312
@wk-mike @automano 

![image](https://user-images.githubusercontent.com/17696228/200337143-2672fe5a-c20b-4eb5-9a38-9b1ff36416ea.png)
![image](https://user-images.githubusercontent.com/17696228/200337240-dc1bcc84-2139-4a71-b40a-f12de52e821d.png)
![image](https://user-images.githubusercontent.com/17696228/200337286-dc2a4f96-83a8-473a-a9e0-960b1928a520.png)

**Comment by automano** [comment]
@yishibakaien 可以的，按照你这个操作了一下。主要我想传到B站上面去。之前传上去也都是乱码，用你这个带编码，再保存成UTF-8的可以了。

**Comment by automano** [comment]
> 我碰到了和你一样的问题，直接运行 `autocut -t ./videos/xxx.mp4` 使用的是 CPU 进行处理，如何使用GPU呢？

用GPU的话，先保证你有GPU。然后安装英伟达那一套（驱动，CUDA,cuDNN)。再安装pytorch GPU版本（先看一下这个，因为还不支持最新的英伟达版本，我装的v11.7）。google一堆教程，搜一下。要注意的点就是版本要对上。还有pip的路径要加到环境变量里面。

**Comment by yishibakaien** [comment]
> > 我碰到了和你一样的问题，直接运行 `autocut -t ./videos/xxx.mp4` 使用的是 CPU 进行处理，如何使用GPU呢？
> 
> 用GPU的话，先保证你有GPU。然后安装英伟达那一套（驱动，CUDA,cuDNN)。再安装pytorch GPU版本（先看一下这个，因为还不支持最新的英伟达版本，我装的v11.7）。google一堆教程，搜一下。要注意的点就是版本要对上。还有pip的路径要加到环境变量里面。

你好，我有 GPU和、对应的驱动、还有 miniconda 环境。pytorch GPU 版本也有，版本是对的上的，我之前跑过沐神的 jupyter notebook 可以使用GPU的能力。

我这样是不是 pip 没在环境变量里
![image](https://user-images.githubusercontent.com/17696228/200347355-fde1cba6-181d-4b11-8ccb-521c0f52cfdf.png)

但是我命令行中可以看到 pip 版本信息
![image](https://user-images.githubusercontent.com/17696228/200347541-fe196d93-2ca6-4c41-ab52-fe77f41cd553.png)

**Comment by yishibakaien** [comment]
> @yishibakaien 加pip环境变量那步主要是为了直接在命令行跑沐神的命令autocut。应该不影响GPU那里。你试一下看下输出是不是GPU的。
> 
> ```python
> import torch
> print(torch.__version__)
> print(torch.cuda.is_available())
> ```
> 
> ![image](https://user-images.githubusercontent.com/17286982/200349003-c57bcc49-69a1-4009-851f-44378db6bd0b.png)
> 
> 如果跟我这个一样是应该没问题的。 我跑沐神那个命令，看到GPU占用率是拉起来的，应该是用到了GPU了。

这个是通过的，但是我运行的时候显示 我正在使用CPU，然后我看了任务管理器里 CPU 基本拉满，GPU 也有使用，但是使用率不高
![image](https://user-images.githubusercontent.com/17696228/200349575-20a466cb-a664-4c1e-ad91-a604eb62e651.png)
![image](https://user-images.githubusercontent.com/17696228/200349862-868f452f-15b9-40bc-9e65-2c2d3c7f19be.png)

**Comment by automano** [comment]
@yishibakaien 你的上面截图是python3.8，下面截图看起来是python3.10的。是不是装了好几个版本的python呢，没对上。

**Comment by automano** [comment]
> 我是正常的。你改一下显示字符的型号，在vs code右下角有个UTF-8，点一下，改动一下

这个治标不治本，我来看看是哪里的问题。

**Comment by chenqianhe** [comment]
https://github.com/mli/autocut/pull/6
可以试试这个PR不，我这边通过指定编码方式应该解决了这个问题

**Comment by yishibakaien** [comment]
> #6 可以试试这个PR不，我这边通过指定编码方式应该解决了这个问题

你好，我试了下好像没有效果，有什么地方需要特别注意的吗？

**Comment by chenqianhe** [comment]
> > #6 可以试试这个PR不，我这边通过指定编码方式应该解决了这个问题
> 
> 你好，我试了下好像没有效果，有什么地方需要特别注意的吗？

是windows吗？可以发下现在乱码的截图吗，最好是整个屏幕包括可以看到你是用的阅读软件的。
应该是直接用就可以，确定下你更新到了我的代码吗？你可以看下代码，相当于是指定了编码格式到utf8，应该是在utf8读取就正常，看看你读取的时候是指定的格式吗？

**Comment by yishibakaien** [comment]
> > > #6 可以试试这个PR不，我这边通过指定编码方式应该解决了这个问题
> > 
> > 
> > 你好，我试了下好像没有效果，有什么地方需要特别注意的吗？
> 
> 是windows吗？可以发下现在乱码的截图吗，最好是整个屏幕包括可以看到你是用的阅读软件的。 应该是直接用就可以，确定下你更新到了我的代码吗？你可以看下代码，相当于是指定了编码格式到utf8，应该是在utf8读取就正常，看看你读取的时候是指定的格式吗？

我 fork 了沐神的项目，完整代码在这 https://github.com/yishibakaien/autocut 
这个是改动的 commit：https://github.com/yishibakaien/autocut/commit/6648626428b5791f4bea0742bba7d14c924844f2
你可以看一下，和你的效果应该是一样的

**Comment by chenqianhe** [comment]
> > > > #6 可以试试这个PR不，我这边通过指定编码方式应该解决了这个问题
> > > 
> > > 
> > > 你好，我试了下好像没有效果，有什么地方需要特别注意的吗？
> > 
> > 
> > 是windows吗？可以发下现在乱码的截图吗，最好是整个屏幕包括可以看到你是用的阅读软件的。 应该是直接用就可以，确定下你更新到了我的代码吗？你可以看下代码，相当于是指定了编码格式到utf8，应该是在utf8读取就正常，看看你读取的时候是指定的格式吗？
> 
> 我 fork 了沐神的项目，完整代码在这 https://github.com/yishibakaien/autocut 这个是改动的 commit：[yishibakaien@6648626](https://github.com/yishibakaien/autocut/commit/6648626428b5791f4bea0742bba7d14c924844f2) 你可以看一下，和你的效果应该是一样的

直接试下我的？ https://github.com/chenqianhe/autocut

**Comment by yishibakaien** [comment]
> > > > > #6 可以试试这个PR不，我这边通过指定编码方式应该解决了这个问题
> > > > 
> > > > 
> > > > 你好，我试了下好像没有效果，有什么地方需要特别注意的吗？
> > > 
> > > 
> > > 是windows吗？可以发下现在乱码的截图吗，最好是整个屏幕包括可以看到你是用的阅读软件的。 应该是直接用就可以，确定下你更新到了我的代码吗？你可以看下代码，相当于是指定了编码格式到utf8，应该是在utf8读取就正常，看看你读取的时候是指定的格式吗？
> > 
> > 
> > 我 fork 了沐神的项目，完整代码在这 https://github.com/yishibakaien/autocut 这个是改动的 commit：[yishibakaien@6648626](https://github.com/yishibakaien/autocut/commit/6648626428b5791f4bea0742bba7d14c924844f2) 你可以看一下，和你的效果应该是一样的
> 
> 直接试下我的？ https://github.com/chenqianhe/autocut
我试了你的项目，好像还是不行！？ 是我哪里可能出问题了吗
![image](https://user-images.githubusercontent.com/17696228/200484884-24f5e88a-0dcd-46da-bbd4-c25e6be3644b.png)

**Comment by chenqianhe** [comment]
> 

可以看下正确内容应该什么样吗

**Comment by chenqianhe** [comment]
> > > > > > #6 可以试试这个PR不，我这边通过指定编码方式应该解决了这个问题
> > > > > 
> > > > > 
> > > > > 你好，我试了下好像没有效果，有什么地方需要特别注意的吗？
> > > > 
> > > > 
> > > > 是windows吗？可以发下现在乱码的截图吗，最好是整个屏幕包括可以看到你是用的阅读软件的。 应该是直接用就可以，确定下你更新到了我的代码吗？你可以看下代码，相当于是指定了编码格式到utf8，应该是在utf8读取就正常，看看你读取的时候是指定的格式吗？
> > > 
> > > 
> > > 我 fork 了沐神的项目，完整代码在这 https://github.com/yishibakaien/autocut 这个是改动的 commit：[yishibakaien@6648626](https://github.com/yishibakaien/autocut/commit/6648626428b5791f4bea0742bba7d14c924844f2) 你可以看一下，和你的效果应该是一样的
> > 
> > 
> > 直接试下我的？ https://github.com/chenqianhe/autocut
> > 我试了你的项目，好像还是不行！？ 是我哪里可能出问题了吗
> > ![image](https://user-images.githubusercontent.com/17696228/200484884-24f5e88a-0dcd-46da-bbd4-c25e6be3644b.png)

可以看下正确内容应该什么样吗

**Comment by yishibakaien** [comment]
> > > > > > > #6 可以试试这个PR不，我这边通过指定编码方式应该解决了这个问题
> > > > > > 
> > > > > > 
> > > > > > 你好，我试了下好像没有效果，有什么地方需要特别注意的吗？
> > > > > 
> > > > > 
> > > > > 是windows吗？可以发下现在乱码的截图吗，最好是整个屏幕包括可以看到你是用的阅读软件的。 应该是直接用就可以，确定下你更新到了我的代码吗？你可以看下代码，相当于是指定了编码格式到utf8，应该是在utf8读取就正常，看看你读取的时候是指定的格式吗？
> > > > 
> > > > 
> > > > 我 fork 了沐神的项目，完整代码在这 https://github.com/yishibakaien/autocut 这个是改动的 commit：[yishibakaien@6648626](https://github.com/yishibakaien/autocut/commit/6648626428b5791f4bea0742bba7d14c924844f2) 你可以看一下，和你的效果应该是一样的
> > > 
> > > 
> > > 直接试下我的？ https://github.com/chenqianhe/autocut
> > > 我试了你的项目，好像还是不行！？ 是我哪里可能出问题了吗
> > > ![image](https://user-images.githubusercontent.com/17696228/200484884-24f5e88a-0dcd-46da-bbd4-c25e6be3644b.png)
> 
> 可以看下正确内容应该什么样吗

![image](https://user-images.githubusercontent.com/17696228/200485773-f872546c-c4be-4e63-be1e-3c441fa6dcf2.png)

**Comment by chenqianhe** [comment]
> > > > > > > > #6 可以试试这个PR不，我这边通过指定编码方式应该解决了这个问题
> > > > > > > 
> > > > > > > 
> > > > > > > 你好，我试了下好像没有效果，有什么地方需要特别注意的吗？
> > > > > > 
> > > > > > 
> > > > > > 是windows吗？可以发下现在乱码的截图吗，最好是整个屏幕包括可以看到你是用的阅读软件的。 应该是直接用就可以，确定下你更新到了我的代码吗？你可以看下代码，相当于是指定了编码格式到utf8，应该是在utf8读取就正常，看看你读取的时候是指定的格式吗？
> > > > > 
> > > > > 
> > > > > 我 fork 了沐神的项目，完整代码在这 https://github.com/yishibakaien/autocut 这个是改动的 commit：[yishibakaien@6648626](https://github.com/yishibakaien/autocut/commit/6648626428b5791f4bea0742bba7d14c924844f2) 你可以看一下，和你的效果应该是一样的
> > > > 
> > > > 
> > > > 直接试下我的？ https://github.com/chenqianhe/autocut
> > > > 我试了你的项目，好像还是不行！？ 是我哪里可能出问题了吗
> > > > ![image](https://user-images.githubusercontent.com/17696228/200484884-24f5e88a-0dcd-46da-bbd4-c25e6be3644b.png)
> > 
> > 
> > 可以看下正确内容应该什么样吗
> 
> ![image](https://user-images.githubusercontent.com/17696228/200485773-f872546c-c4be-4e63-be1e-3c441fa6dcf2.png)

![image](https://user-images.githubusercontent.com/54462604/200486761-75180f38-0ff6-40a1-80e4-4ca03e11bc55.png)
![image](https://user-images.githubusercontent.com/54462604/200486796-f5af1607-427f-4e8a-8674-604eee33915d.png)

有点奇怪，我这边测试确实是ok了

你这边下了我的新的库有重新安装覆盖掉旧的吗。你可以尝试在我的代码里增加一些print等，再运行，看看是否有对应输出，确认一下运行的程序是否正确

**Comment by yishibakaien** [comment]
> > > > > > > > > #6 可以试试这个PR不，我这边通过指定编码方式应该解决了这个问题
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 你好，我试了下好像没有效果，有什么地方需要特别注意的吗？
> > > > > > > 
> > > > > > > 
> > > > > > > 是windows吗？可以发下现在乱码的截图吗，最好是整个屏幕包括可以看到你是用的阅读软件的。 应该是直接用就可以，确定下你更新到了我的代码吗？你可以看下代码，相当于是指定了编码格式到utf8，应该是在utf8读取就正常，看看你读取的时候是指定的格式吗？
> > > > > > 
> > > > > > 
> > > > > > 我 fork 了沐神的项目，完整代码在这 https://github.com/yishibakaien/autocut 这个是改动的 commit：[yishibakaien@6648626](https://github.com/yishibakaien/autocut/commit/6648626428b5791f4bea0742bba7d14c924844f2) 你可以看一下，和你的效果应该是一样的
> > > > > 
> > > > > 
> > > > > 直接试下我的？ https://github.com/chenqianhe/autocut
> > > > > 我试了你的项目，好像还是不行！？ 是我哪里可能出问题了吗
> > > > > ![image](https://user-images.githubusercontent.com/17696228/200484884-24f5e88a-0dcd-46da-bbd4-c25e6be3644b.png)
> > > 
> > > 
> > > 可以看下正确内容应该什么样吗
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/17696228/200485773-f872546c-c4be-4e63-be1e-3c441fa6dcf2.png)
> 
> ![image](https://user-images.githubusercontent.com/54462604/200486761-75180f38-0ff6-40a1-80e4-4ca03e11bc55.png) ![image](https://user-images.githubusercontent.com/54462604/200486796-f5af1607-427f-4e8a-8674-604eee33915d.png)
> 
> 有点奇怪，我这边测试确实是ok了
> 
> 你这边下了我的新的库有重新安装覆盖掉旧的吗。你可以尝试在我的代码里增加一些print等，再运行，看看是否有对应输出，确认一下运行的程序是否正确

没有下载你的新库，应该不是库的问题吧.....，python不太熟练，我先debug一下

**Comment by chenqianhe** [comment]
> > > > > > > > > > #6 可以试试这个PR不，我这边通过指定编码方式应该解决了这个问题
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 你好，我试了下好像没有效果，有什么地方需要特别注意的吗？
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 是windows吗？可以发下现在乱码的截图吗，最好是整个屏幕包括可以看到你是用的阅读软件的。 应该是直接用就可以，确定下你更新到了我的代码吗？你可以看下代码，相当于是指定了编码格式到utf8，应该是在utf8读取就正常，看看你读取的时候是指定的格式吗？
> > > > > > > 
> > > > > > > 
> > > > > > > 我 fork 了沐神的项目，完整代码在这 https://github.com/yishibakaien/autocut 这个是改动的 commit：[yishibakaien@6648626](https://github.com/yishibakaien/autocut/commit/6648626428b5791f4bea0742bba7d14c924844f2) 你可以看一下，和你的效果应该是一样的
> > > > > > 
> > > > > > 
> > > > > > 直接试下我的？ https://github.com/chenqianhe/autocut
> > > > > > 我试了你的项目，好像还是不行！？ 是我哪里可能出问题了吗
> > > > > > ![image](https://user-images.githubusercontent.com/17696228/200484884-24f5e88a-0dcd-46da-bbd4-c25e6be3644b.png)
> > > > 
> > > > 
> > > > 可以看下正确内容应该什么样吗
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/17696228/200485773-f872546c-c4be-4e63-be1e-3c441fa6dcf2.png)
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/54462604/200486761-75180f38-0ff6-40a1-80e4-4ca03e11bc55.png) ![image](https://user-images.githubusercontent.com/54462604/200486796-f5af1607-427f-4e8a-8674-604eee33915d.png)
> > 有点奇怪，我这边测试确实是ok了
> > 你这边下了我的新的库有重新安装覆盖掉旧的吗。你可以尝试在我的代码里增加一些print等，再运行，看看是否有对应输出，确认一下运行的程序是否正确
> 
> 没有下载你的新库，应该不是库的问题吧.....，python不太熟练，我先debug一下

不是说依赖库的意思，指的是autocut，先确认下运行的我的autocut，而不是旧的。可以尝试在我的代码里增加一些print等，再运行，看看是否有对应输出，确认一下运行的程序是否是新的autocut

**Comment by yishibakaien** [comment]
> > > > > > > > > > > #6 可以试试这个PR不，我这边通过指定编码方式应该解决了这个问题
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 你好，我试了下好像没有效果，有什么地方需要特别注意的吗？
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 是windows吗？可以发下现在乱码的截图吗，最好是整个屏幕包括可以看到你是用的阅读软件的。 应该是直接用就可以，确定下你更新到了我的代码吗？你可以看下代码，相当于是指定了编码格式到utf8，应该是在utf8读取就正常，看看你读取的时候是指定的格式吗？
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 我 fork 了沐神的项目，完整代码在这 https://github.com/yishibakaien/autocut 这个是改动的 commit：[yishibakaien@6648626](https://github.com/yishibakaien/autocut/commit/6648626428b5791f4bea0742bba7d14c924844f2) 你可以看一下，和你的效果应该是一样的
> > > > > > > 
> > > > > > > 
> > > > > > > 直接试下我的？ https://github.com/chenqianhe/autocut
> > > > > > > 我试了你的项目，好像还是不行！？ 是我哪里可能出问题了吗
> > > > > > > ![image](https://user-images.githubusercontent.com/17696228/200484884-24f5e88a-0dcd-46da-bbd4-c25e6be3644b.png)
> > > > > 
> > > > > 
> > > > > 可以看下正确内容应该什么样吗
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/17696228/200485773-f872546c-c4be-4e63-be1e-3c441fa6dcf2.png)
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/54462604/200486761-75180f38-0ff6-40a1-80e4-4ca03e11bc55.png) ![image](https://user-images.githubusercontent.com/54462604/200486796-f5af1607-427f-4e8a-8674-604eee33915d.png)
> > > 有点奇怪，我这边测试确实是ok了
> > > 你这边下了我的新的库有重新安装覆盖掉旧的吗。你可以尝试在我的代码里增加一些print等，再运行，看看是否有对应输出，确认一下运行的程序是否正确
> > 
> > 
> > 没有下载你的新库，应该不是库的问题吧.....，python不太熟练，我先debug一下
> 
> 不是说依赖库的意思，指的是autocut，先确认下运行的我的autocut，而不是旧的。可以尝试在我的代码里增加一些print等，再运行，看看是否有对应输出，确认一下运行的程序是否是新的autocut

我这个是不是没有执行你的新 autocut ?
![image](https://user-images.githubusercontent.com/17696228/200495354-9c35f992-69cc-4c15-9c72-516db2541f2e.png)

**Comment by chenqianhe** [comment]
> > > > > > > > > > > > #6 可以试试这个PR不，我这边通过指定编码方式应该解决了这个问题
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > 你好，我试了下好像没有效果，有什么地方需要特别注意的吗？
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 是windows吗？可以发下现在乱码的截图吗，最好是整个屏幕包括可以看到你是用的阅读软件的。 应该是直接用就可以，确定下你更新到了我的代码吗？你可以看下代码，相当于是指定了编码格式到utf8，应该是在utf8读取就正常，看看你读取的时候是指定的格式吗？
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 我 fork 了沐神的项目，完整代码在这 https://github.com/yishibakaien/autocut 这个是改动的 commit：[yishibakaien@6648626](https://github.com/yishibakaien/autocut/commit/6648626428b5791f4bea0742bba7d14c924844f2) 你可以看一下，和你的效果应该是一样的
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 直接试下我的？ https://github.com/chenqianhe/autocut
> > > > > > > > 我试了你的项目，好像还是不行！？ 是我哪里可能出问题了吗
> > > > > > > > ![image](https://user-images.githubusercontent.com/17696228/200484884-24f5e88a-0dcd-46da-bbd4-c25e6be3644b.png)
> > > > > > 
> > > > > > 
> > > > > > 可以看下正确内容应该什么样吗
> > > > > 
> > > > > 
> > > > > ![image](https://user-images.githubusercontent.com/17696228/200485773-f872546c-c4be-4e63-be1e-3c441fa6dcf2.png)
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/54462604/200486761-75180f38-0ff6-40a1-80e4-4ca03e11bc55.png) ![image](https://user-images.githubusercontent.com/54462604/200486796-f5af1607-427f-4e8a-8674-604eee33915d.png)
> > > > 有点奇怪，我这边测试确实是ok了
> > > > 你这边下了我的新的库有重新安装覆盖掉旧的吗。你可以尝试在我的代码里增加一些print等，再运行，看看是否有对应输出，确认一下运行的程序是否正确
> > > 
> > > 
> > > 没有下载你的新库，应该不是库的问题吧.....，python不太熟练，我先debug一下
> > 
> > 
> > 不是说依赖库的意思，指的是autocut，先确认下运行的我的autocut，而不是旧的。可以尝试在我的代码里增加一些print等，再运行，看看是否有对应输出，确认一下运行的程序是否是新的autocut
> 
> 我这个是不是没有执行你的新 autocut ? ![image](https://user-images.githubusercontent.com/17696228/200495354-9c35f992-69cc-4c15-9c72-516db2541f2e.png)

是的，没有运行新代码，你可以重新开个虚拟环境试试

**Comment by yishibakaien** [comment]
> > > > > > > > > > > > > #6 可以试试这个PR不，我这边通过指定编码方式应该解决了这个问题
> > > > > > > > > > > > 
> > > > > > > > > > > > 
> > > > > > > > > > > > 你好，我试了下好像没有效果，有什么地方需要特别注意的吗？
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > 是windows吗？可以发下现在乱码的截图吗，最好是整个屏幕包括可以看到你是用的阅读软件的。 应该是直接用就可以，确定下你更新到了我的代码吗？你可以看下代码，相当于是指定了编码格式到utf8，应该是在utf8读取就正常，看看你读取的时候是指定的格式吗？
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 我 fork 了沐神的项目，完整代码在这 https://github.com/yishibakaien/autocut 这个是改动的 commit：[yishibakaien@6648626](https://github.com/yishibakaien/autocut/commit/6648626428b5791f4bea0742bba7d14c924844f2) 你可以看一下，和你的效果应该是一样的
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 直接试下我的？ https://github.com/chenqianhe/autocut
> > > > > > > > > 我试了你的项目，好像还是不行！？ 是我哪里可能出问题了吗
> > > > > > > > > ![image](https://user-images.githubusercontent.com/17696228/200484884-24f5e88a-0dcd-46da-bbd4-c25e6be3644b.png)
> > > > > > > 
> > > > > > > 
> > > > > > > 可以看下正确内容应该什么样吗
> > > > > > 
> > > > > > 
> > > > > > ![image](https://user-images.githubusercontent.com/17696228/200485773-f872546c-c4be-4e63-be1e-3c441fa6dcf2.png)
> > > > > 
> > > > > 
> > > > > ![image](https://user-images.githubusercontent.com/54462604/200486761-75180f38-0ff6-40a1-80e4-4ca03e11bc55.png) ![image](https://user-images.githubusercontent.com/54462604/200486796-f5af1607-427f-4e8a-8674-604eee33915d.png)
> > > > > 有点奇怪，我这边测试确实是ok了
> > > > > 你这边下了我的新的库有重新安装覆盖掉旧的吗。你可以尝试在我的代码里增加一些print等，再运行，看看是否有对应输出，确认一下运行的程序是否正确
> > > > 
> > > > 
> > > > 没有下载你的新库，应该不是库的问题吧.....，python不太熟练，我先debug一下
> > > 
> > > 
> > > 不是说依赖库的意思，指的是autocut，先确认下运行的我的autocut，而不是旧的。可以尝试在我的代码里增加一些print等，再运行，看看是否有对应输出，确认一下运行的程序是否是新的autocut
> > 
> > 
> > 我这个是不是没有执行你的新 autocut ? ![image](https://user-images.githubusercontent.com/17696228/200495354-9c35f992-69cc-4c15-9c72-516db2541f2e.png)
> 
> 是的，没有运行新代码，你可以重新开个虚拟环境试试

能不能请教一下怎么开新环境....，我是新手....不好意思

**Comment by chenqianhe** [comment]
> > > > > > > > > > > > > > #6 可以试试这个PR不，我这边通过指定编码方式应该解决了这个问题
> > > > > > > > > > > > > 
> > > > > > > > > > > > > 
> > > > > > > > > > > > > 你好，我试了下好像没有效果，有什么地方需要特别注意的吗？
> > > > > > > > > > > > 
> > > > > > > > > > > > 
> > > > > > > > > > > > 是windows吗？可以发下现在乱码的截图吗，最好是整个屏幕包括可以看到你是用的阅读软件的。 应该是直接用就可以，确定下你更新到了我的代码吗？你可以看下代码，相当于是指定了编码格式到utf8，应该是在utf8读取就正常，看看你读取的时候是指定的格式吗？
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > 我 fork 了沐神的项目，完整代码在这 https://github.com/yishibakaien/autocut 这个是改动的 commit：[yishibakaien@6648626](https://github.com/yishibakaien/autocut/commit/6648626428b5791f4bea0742bba7d14c924844f2) 你可以看一下，和你的效果应该是一样的
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 直接试下我的？ https://github.com/chenqianhe/autocut
> > > > > > > > > > 我试了你的项目，好像还是不行！？ 是我哪里可能出问题了吗
> > > > > > > > > > ![image](https://user-images.githubusercontent.com/17696228/200484884-24f5e88a-0dcd-46da-bbd4-c25e6be3644b.png)
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 可以看下正确内容应该什么样吗
> > > > > > > 
> > > > > > > 
> > > > > > > ![image](https://user-images.githubusercontent.com/17696228/200485773-f872546c-c4be-4e63-be1e-3c441fa6dcf2.png)
> > > > > > 
> > > > > > 
> > > > > > ![image](https://user-images.githubusercontent.com/54462604/200486761-75180f38-0ff6-40a1-80e4-4ca03e11bc55.png) ![image](https://user-images.githubusercontent.com/54462604/200486796-f5af1607-427f-4e8a-8674-604eee33915d.png)
> > > > > > 有点奇怪，我这边测试确实是ok了
> > > > > > 你这边下了我的新的库有重新安装覆盖掉旧的吗。你可以尝试在我的代码里增加一些print等，再运行，看看是否有对应输出，确认一下运行的程序是否正确
> > > > > 
> > > > > 
> > > > > 没有下载你的新库，应该不是库的问题吧.....，python不太熟练，我先debug一下
> > > > 
> > > > 
> > > > 不是说依赖库的意思，指的是autocut，先确认下运行的我的autocut，而不是旧的。可以尝试在我的代码里增加一些print等，再运行，看看是否有对应输出，确认一下运行的程序是否是新的autocut
> > > 
> > > 
> > > 我这个是不是没有执行你的新 autocut ? ![image](https://user-images.githubusercontent.com/17696228/200495354-9c35f992-69cc-4c15-9c72-516db2541f2e.png)
> > 
> > 
> > 是的，没有运行新代码，你可以重新开个虚拟环境试试
> 
> 能不能请教一下怎么开新环境....，我是新手....不好意思

https://blog.csdn.net/weixin_50637551/article/details/124556453

试试这个？有问题可以查一查看看

**Comment by yishibakaien** [comment]
> > > > > > > > > > > > > > > #6 可以试试这个PR不，我这边通过指定编码方式应该解决了这个问题
> > > > > > > > > > > > > > 
> > > > > > > > > > > > > > 
> > > > > > > > > > > > > > 你好，我试了下好像没有效果，有什么地方需要特别注意的吗？
> > > > > > > > > > > > > 
> > > > > > > > > > > > > 
> > > > > > > > > > > > > 是windows吗？可以发下现在乱码的截图吗，最好是整个屏幕包括可以看到你是用的阅读软件的。 应该是直接用就可以，确定下你更新到了我的代码吗？你可以看下代码，相当于是指定了编码格式到utf8，应该是在utf8读取就正常，看看你读取的时候是指定的格式吗？
> > > > > > > > > > > > 
> > > > > > > > > > > > 
> > > > > > > > > > > > 我 fork 了沐神的项目，完整代码在这 https://github.com/yishibakaien/autocut 这个是改动的 commit：[yishibakaien@6648626](https://github.com/yishibakaien/autocut/commit/6648626428b5791f4bea0742bba7d14c924844f2) 你可以看一下，和你的效果应该是一样的
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > 直接试下我的？ https://github.com/chenqianhe/autocut
> > > > > > > > > > > 我试了你的项目，好像还是不行！？ 是我哪里可能出问题了吗
> > > > > > > > > > > ![image](https://user-images.githubusercontent.com/17696228/200484884-24f5e88a-0dcd-46da-bbd4-c25e6be3644b.png)
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 可以看下正确内容应该什么样吗
> > > > > > > > 
> > > > > > > > 
> > > > > > > > ![image](https://user-images.githubusercontent.com/17696228/200485773-f872546c-c4be-4e63-be1e-3c441fa6dcf2.png)
> > > > > > > 
> > > > > > > 
> > > > > > > ![image](https://user-images.githubusercontent.com/54462604/200486761-75180f38-0ff6-40a1-80e4-4ca03e11bc55.png) ![image](https://user-images.githubusercontent.com/54462604/200486796-f5af1607-427f-4e8a-8674-604eee33915d.png)
> > > > > > > 有点奇怪，我这边测试确实是ok了
> > > > > > > 你这边下了我的新的库有重新安装覆盖掉旧的吗。你可以尝试在我的代码里增加一些print等，再运行，看看是否有对应输出，确认一下运行的程序是否正确
> > > > > > 
> > > > > > 
> > > > > > 没有下载你的新库，应该不是库的问题吧.....，python不太熟练，我先debug一下
> > > > > 
> > > > > 
> > > > > 不是说依赖库的意思，指的是autocut，先确认下运行的我的autocut，而不是旧的。可以尝试在我的代码里增加一些print等，再运行，看看是否有对应输出，确认一下运行的程序是否是新的autocut
> > > > 
> > > > 
> > > > 我这个是不是没有执行你的新 autocut ? ![image](https://user-images.githubusercontent.com/17696228/200495354-9c35f992-69cc-4c15-9c72-516db2541f2e.png)
> > > 
> > > 
> > > 是的，没有运行新代码，你可以重新开个虚拟环境试试
> > 
> > 
> > 能不能请教一下怎么开新环境....，我是新手....不好意思
> 
> https://blog.csdn.net/weixin_50637551/article/details/124556453
> 
> 试试这个？有问题可以查一查看看

非常感谢！！我去研究一下，有结果了在这里同步

**Comment by yishibakaien** [comment]
@chenqianhe  非常感谢！！字符集不正确问题已解决！
我删除了 miniconda 下安装的 autocut 包文件 ` d:\miniconda\envs\dev\lib\site-packages\autocut-0.0.1-py3.10.egg` 
然后重新执行一遍 `python setup.py install` 注册了你的项目的 `autocut` 命令后解决了该问题

![image](https://user-images.githubusercontent.com/17696228/200716497-de551f5e-3ff2-4b39-8621-f4e3c9f5966f.png)
![image](https://user-images.githubusercontent.com/17696228/200716722-6a62f58a-8cff-41e5-9b55-143a11d2a7ff.png)

**Comment by automano** [comment]
No more questions here, will close this.
