### ISSUE TITLE
autocut -c命令没有任何效果

### ISSUE THREAD

**Issue by imcaptor** [mli/autocut#101]
先生成了0010101.md，然后编辑0010101.md选了几行字幕。
执行下面命令：
autocut -c 0010101.mp4 0010101.srt 0010101.md

很快结束了，没有产生任何输出文件。

**Comment by chenqianhe** [comment]
方便给相关文件我来测试下吗

**Comment by chenqianhe** [comment]
编辑md文件时还需要选中已完成编辑那里

**Comment by chenqianhe** [comment]
太久没有回复，如果有更新信息可以重新开起
