### ISSUE TITLE
Cutting issue

### ISSUE THREAD

**Issue by nPokemon** [mli/autocut#105]
Download , and transcript video , but when I using cut, it did not do anything.
autocut -c DownloadVideos/Breaking_Bad_2_-_Official_Trailer.mp4 DownloadVideos/Breaking_Bad_2_-_Official_Trailer.srt DownloadVideos/Breaking_Bad_2_-_Official_Trailer.md --device cuda --lang en

- [X] <-- Mark if you are done editing.

<video controls="true" allowfullscreen="true"> <source src="Breaking_Bad_2_-_Official_Trailer.mp4" type="video/mp4"> </video>

Texts generated from [Breaking_Bad_2_-_Official_Trailer.srt](Breaking_Bad_2_-_Official_Trailer.srt).Mark the sentences to keep for autocut.
The format is [subtitle_index,duration_in_second] subtitle context.

- [ ] [1,00:00]   Hi, this is Bryan Cranston.
- [ ] [2,00:01]   The official trailer for Breaking Bad 2 starts in 3.
- [ ] [3,00:05]   < No Speech >
- [ ] [4,00:10]   全是我做的,全是发生的
- [ ] [5,00:15]   来源于那一个决定
- [ ] [6,00:19]   你想要一颗金属吗?
- [ ] [7,00:21]   那一个决定
- [ ] [8,00:22]   他在那里!
- [ ] [9,00:24]   我们是狐狸!
- [ ] [10,00:26]  快点!
- [ ] [11,00:28]  < No Speech >
- [ ] [12,00:35]  You did not kill Uncle Hank
- [ ] [13,00:38]  Uncle Hank is still alive
- [ ] [14,00:42]  < No Speech >
- [ ] [15,00:43]  I'm gonna avenge your death
- [ ] [16,00:45]  Take out that Neo-Nazi scum
- [ ] [17,00:47]  < No Speech >
- [ ] [18,00:51]  嘿玛利亚,我还活著!
- [ ] [19,00:54]  < No Speech >
- [ ] [20,00:55]  耶~~
- [ ] [21,00:57]  我不会被埋在森林里吧
- [ ] [22,00:59]  < No Speech >
- [ ] [23,01:01]  嘿嘿
- [ ] [24,01:02]  < No Speech >
- [ ] [25,01:07]  你还好吗?
- [ ] [26,01:08]  停止停止停止
- [X] [27,01:10]  停止停止停止
- [ ] [28,01:12]  < No Speech >
- [ ] [29,01:24]  你好
- [ ] [30,01:24]  给我查出
- [ ] [31,01:25]  哪里来的毒癖
- [ ] [32,01:27]  付钱的人
- [ ] [33,01:28]  < No Speech >
- [ ] [34,01:29]  沉静点
- [ ] [35,01:31]  我客人
- [ ] [36,01:32]  不管哪个病人
- [ ] [37,01:33]  师兄
- [ ] [38,01:34]  你这样太智障了
- [ ] [39,01:35]  我bruising了好多年
- [ ] [40,01:38]  但这么一刀
- [ ] [41,01:39]  炸大脑
- [ ] [42,01:40]  < No Speech >
- [X] [43,01:44]  我是白宫法官,你违反了他的宪法
- [ ] [44,01:48]  你们这些人为什么不让我死在安和的地方
- [ ] [45,01:50]  放下,没有人在跟你说话
- [ ] [46,01:52]  他没有跟我们说话
- [ ] [47,01:54]  他很混乱,他被人家当孩子的时候摔在头上
- [ ] [48,01:58]  < No Speech >
- [ ] [49,02:21]  Agent Schrader, any good suspects lately?
- [ ] [50,02:24]  < No Speech >
- [ ] [51,02:40]  我会镇压你的!
- [ ] [52,02:42]  < No Speech >
- [ ] [53,02:57]  不如打911
- [ ] [54,02:59]  < No Speech >
- [ ] [55,03:01]  然后我的一首民族歌
- [ ] [56,03:03]  《异世界链接》
- [ ] [57,03:06]  < No Speech >
- [ ] [58,03:19]  给你们几分钟
- [ ] [59,03:20]  记得
- [X] [60,03:21]  你还是个小孩
- [ ] [61,03:22]  < No Speech >
- [ ] [62,03:27]  肉 aerial
- [ ] [63,03:41]  德诺查尔斯
- [ ] [64,03:42]  And therefore
- [ ] [65,03:43]  your
- [ ] [66,03:44]  use
- [ ] [67,03:46]  < No Speech >
- [ ] [68,04:05]  收货
- [ ] [69,04:06]  < No Speech >
- [ ] [70,04:08]  I'm in danger, Skyler.
- [ ] [71,04:10]  I am in the danger.
- [ ] [72,04:12]  My name is Skyler White, yo.
- [ ] [73,04:14]  My husband is Walter White, yo.
- [ ] [74,04:16]  You think you can steal from us and just walk away?
- [ ] [75,04:18]  Uh-huh.
- [ ] [76,04:20]  Yeah, science, bitch!
- [ ] [77,04:22]  I do not fear, for you are with me.
- [ ] [78,04:25]  They took everything from me.
- [ ] [79,04:27]  Why don't you kill me, bro?
- [ ] [80,04:28]  I'm a son of a bitch, I'm gonna kill him.
- [ ] [81,04:30]  Where are they?
- [ ] [82,04:31]  I'm gonna kill that bitch.
- [ ] [83,04:33]  Chuck was alive, and now he's dead, and now he's alive.
- [ ] [84,04:35]  You passed the bar, you know?
- [ ] [85,04:37]  I apologize.
- [ ] [86,04:38]  It's all right, don't sweat it. It's all good.
- [ ] [87,04:40]  Man!
- [ ] [88,04:41]  What a shit joke!
- [ ] [89,04:43]  < No Speech >
- [ ] [90,04:45]  算是得ス
- [ ] [91,04:48]  字幕 by joshua
- [X] [92,05:10]  下面留言这里有别的视频哦
- [ ] [93,05:16]  display
- [ ] [94,05:16]  < No Speech >
- [ ] [95,05:19]  字幕by索兰娅
- [ ] [96,05:20]  < No Speech >
- [ ] [97,05:27]  Where were the two bodies?
- [ ] [98,05:29]  You, this is all your fault.
- [ ] [99,05:31]  Stay exactly where you are.
- [ ] [100,05:34] < No Speech >
- [ ] [101,05:46] Someone help me! Help me please!
- [ ] [102,05:49] < No Speech >
- [ ] [103,05:53] The only people left on the street are the sort that enjoy the chaos
- [ ] [104,05:57] Tonight, Gotham's relying on one man to save us all
- [ ] [105,06:00] Hello, Saul
- [ ] [106,06:02] Good at man
- [ ] [107,06:03] Oh, look at you
- [ ] [108,06:04] Should I call the FBI and tell them I found the Joker?
- [ ] [109,06:08] I thought my jokes were bad
- [ ] [110,06:10] It's a joke, Joker
- [ ] [111,06:12] The Joker is a complete amateur
- [ ] [112,06:15] It's simple, we kill the Batman
- [ ] [113,06:18] You grow more gorgeous by the minute

**Comment by chenqianhe** [comment]
I'm not sure if you have solved this problem, but I will now try to reproduce and solve the problem

**Comment by chenqianhe** [comment]
I tested in other files and did not encounter this issue. Have you solved the problem after trying? Or can you provide audio or video files?
