### ISSUE TITLE
PyTorch has CUDA version 11.8 whereas TorchAudio has CUDA version 11.7 

### ISSUE THREAD

**Issue by why-is-me** [mli/autocut#106]
RuntimeError: Detected that PyTorch and TorchAudio were compiled with different CUDA versions. PyTorch has CUDA version 11.8 whereas TorchAudio has CUDA version 11.7. Please install the TorchAudio version that matches your PyTorch version.

my TorchAudio version is 2.0.2 ，Does the latest version of TorchAudio not support CUDA 11.8？

**Comment by chenqianhe** [comment]
You should ask the relevant maintenance personnel of Pytorch, as we cannot solve this issue
