### ISSUE TITLE
求职，毕业即失业，在家鬼混3年

### ISSUE THREAD

**Issue by StevenJokess** [mli/autocut#109]
求职，毕业即失业，在家鬼混3年
- 金融方面：2020届的山西大学金融学专业的毕业生，获得三好学生学业奖学金，拥有会计、证券、基金从业证书，毕业论文是用Python的Statsmodel库里的VAR模型完成的《中美股市的联动性分析》
- AI方面：大一参加数学建模了解了神经网络算法，后在网络金融课分享了鱼书的ppt，得知金融方面的非结构信息常用深度学习算法，之后阅读过二十几本人工智能相关书籍，在20年用4个月自学完了《动手学深度学习》预览版并动手翻译MXNet到PyTorch、TF2的GAN\DCGAN，复现PyTorch、DJL等一系列深度学习移动端框架的Demo。
- 产品经理方面：虽然没有工作经历，但还是努力修炼了一系列的能力。战略能力上，在百度一面失败后，考虑到了百度开发者版的想法。沟通能力上，与MXNet的开发者交流无人社区冷淡情况。学习上，学习十余本产品有关的书，并自行总结了AI产品经理的工作内容和技能要求，用Docker部署成《To be AI PM》书。
- 体能方面：跳绳比赛成绩:30s单摇:66;30s双摇:60;三摇:11个;·在4*30男子团体单摇比赛,作为非体院唯一绳没断的第四棒,团体一同跳250.取得市和省级铜牌。（B站跳绳视频：
https://b23.tv/ZqAkEQu）随后,作为非社团成员,文案宣传跳绳燃脂效率高、方便,招新翻四倍。还有初级教练、裁判证;曾会单手俯卧撑、深蹲10个+；

更多AI产品经理内容，可见：https://stevenjokess.github.io/2bPM/get_started.html
AI时代批判与共产主义意识形态输出，见 https://stevenjokess.github.io/2bPM/AI_critical.html
更多及时内容，进QQ群：171097552
联系我：867907127@qq.com

**Comment by chenqianhe** [comment]
首先祝你能找的好的工作！其次由于您的 issue 与仓库无关，并且涉及意识形态等不适合该仓库的内容因此我们需要进行关闭和删除。

**Comment by chenqianhe** [comment]
@mli Timely deletion and review required!
