### ISSUE TITLE
识别无人说话的音频，会出现“字幕制作人Zither Harp”，这个怎么删掉

### ISSUE THREAD

**Issue by yfq512** [mli/autocut#111]

**Comment by chenqianhe** [comment]
首先这个问题产生是由于模型本身造成的，所以说是很不好解决的一个问题。然后目前的话就是说用VAD这样的模型把没有人声的部分给过滤掉

**Comment by yfq512** [comment]
谢谢解答，我测试了几个无声的音频，都会出现 “字幕制作人”， “Zither Harp”这两种文字，如果是固定出现这两种倒是可以判断一下给他过滤掉，不过我不清楚还会不会出现其他的文字，这个问题你清楚么

**Comment by chenqianhe** [comment]
> 谢谢解答，我测试了几个无声的音频，都会出现 “字幕制作人”， “Zither Harp”这两种文字，如果是固定出现这两种倒是可以判断一下给他过滤掉，不过我不清楚还会不会出现其他的文字，这个问题你清楚么

这个是不固定的
