### ISSUE TITLE
求助：使用GPU计算视频遇到的问题

### ISSUE THREAD

**Issue by cen798** [mli/autocut#125]
请教各位佬，我根据项目安装步骤，在GPU运行时，遇到以下画面的情况，docker中的镜像已经运行。接下来需要输入什么命令，才能继续开始运算视频并生成md文件，具体要如何操作？（视频文件在 d:/test文件夹中）谢谢指导！！！
![343b9a0736dfd4b9f6c7f71f053346b](https://github.com/mli/autocut/assets/104133332/a0fec128-6dee-4e0d-89cb-c141e857c4ee)

**Comment by chenqianhe** [comment]
我个人理解使用 docker 的话就需要所有操作都在 docker 容器内完成。也就是进入容器后按照正常流程来使用 autocut，为了方便的话可以进行部分文件夹的映射，详见 docker 相关教程。如果不熟的话可以直接在本机跑，会相对简单一些。

**Comment by cen798** [comment]
谢谢大佬解答，我再试试docker里面用gpu运行，主要想提高生成效率。本地运行已经跑通。
