### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by tumuyan** [mli/autocut#15]
1. 因为国内的网络问题，对很多不使用Python的人来说（比如我），本地安装依赖会有一些困难，希望能够提供免安装依赖包的一键运行包（比如不包含Python本体但是包含whisper，模型和src）。
2. 虽然我看到您的视频主要在讲whisper，但是也希望这个软件可以直接使用其他软件生成的字幕文件。
3. 希望可以增加一个功能，根据字幕编辑的章节标记（比如使用md的标题标记#），把视频输出为几个片段，方便使用视频剪辑工具做进一步的处理。输出的片段也可以用序号+设定的章节来命名。
4. （程序我还没有跑起来，不太确定是不是已有这样的功能）如果我把字幕的时间顺序打乱，比如第10句放到第1句前，输出视频内容会变更为第一句在第10句前前。

谢谢

**Comment by chenqianhe** [comment]
- 第一个的话，一般来说涉及深度学习的都不太好去py打包（py打包本来就不太好做），这个涉及到各种硬件配置和环境
https://github.com/QPT-Family/QPT
https://github.com/Nuitka/Nuitka
这俩是针对涉及ai打包比较好的库，不知道有人愿意试试不。
- 第二个是支持的。 现在字幕文件用的是通用的字幕格式。

**Comment by tumuyan** [comment]
> * 第二个是支持的。 现在字幕文件用的是通用的字幕格式

但是选项中似乎并没有输入视频和字幕，输出md文件的功能？只能输入视频，或者输入视频+markdown文件+字幕文件

**Comment by chenqianhe** [comment]
> > * 第二个是支持的。 现在字幕文件用的是通用的字幕格式
> 
> 但是选项中似乎并没有输入视频和字幕，输出md文件的功能？只能输入视频，或者输入视频+markdown文件+字幕文件

可以直接根据srt进行剪辑；或者你希望srt转md的话那其实把代码里面的srt转md拿出来一个单独函数并暴露出来就行；这个改造很简单就可以支持。我有空的话可以晚点搞下
> 如果不习惯Markdown文件，你也可以直接在srt文件里删除不要的句子，在剪切时不传入md文件名即可。就是 autocut -c 22-52-00.mp4 22-52-00.srt

**Comment by chenqianhe** [comment]
> > * 第二个是支持的。 现在字幕文件用的是通用的字幕格式
> 
> 但是选项中似乎并没有输入视频和字幕，输出md文件的功能？只能输入视频，或者输入视频+markdown文件+字幕文件

https://github.com/mli/autocut/pull/18

试试：https://github.com/chenqianhe/autocut

但是目前剪切还有问题，不会剪切srt文件，晚点再看看怎么完善

**Comment by chenqianhe** [comment]
> > > * 第二个是支持的。 现在字幕文件用的是通用的字幕格式
> > 
> > 
> > 但是选项中似乎并没有输入视频和字幕，输出md文件的功能？只能输入视频，或者输入视频+markdown文件+字幕文件
> 
> #18
> 
> 试试：https://github.com/chenqianhe/autocut
> 
> 但是目前剪切还有问题，不会剪切srt文件，晚点再看看怎么完善

已修复，包括第四个顺序问题 https://github.com/mli/autocut/pull/18

**Comment by tumuyan** [comment]
感谢，晚上我试试。
我对Python不熟，想请教下，如果whisper src这几个依赖已经安装过，然后直接下载你仓库的代码解压，不使用pip安装（毕竟已经pip安装过一个了），能不能直接用Python命令来使用？

**Comment by tumuyan** [comment]
测试字幕转markdown是正常的，但是通过调整字幕或md文件中行的顺序，均不能实现输出的视频和字幕的内容的顺序。

**Comment by chenqianhe** [comment]
> 测试字幕转markdown是正常的，但是通过调整字幕或md文件中行的顺序，均不能实现输出的视频和字幕的内容的顺序。

只保证剪切会按照时间顺序来，乱序字幕和md不影响最后结果。要用字幕顺序做剪辑怪怪的

https://github.com/chenqianhe/autocut/blob/6fe70429b5fd8e270a337f19443eeef51ba41819/autocut/cut.py#L116

**Comment by tumuyan** [comment]
😭

**Comment by chenqianhe** [comment]
> > 测试字幕转markdown是正常的，但是通过调整字幕或md文件中行的顺序，均不能实现输出的视频和字幕的内容的顺序。
> 
> 只保证剪切会按照时间顺序来，乱序字幕和md不影响最后结果。要用字幕顺序做剪辑怪怪的
> 
> https://github.com/chenqianhe/autocut/blob/6fe70429b5fd8e270a337f19443eeef51ba41819/autocut/cut.py#L116

你可以试试把我代码下下来，把这一行注释了试试？

**Comment by mli** [comment]
其实也可以加上可以改变顺序逻辑，不过我先要测试一下效果，希望不要减出来的视频特别跳

**Comment by chenqianhe** [comment]
> 其实也可以加上可以改变顺序逻辑，不过我先要测试一下效果，希望不要减出来的视频特别跳

目前应该就是有的，我看代码是没有强制按照时间顺序进行剪切合并，我还额外加了强制按照时间顺序cut合并，就是这个稍微有点怪，会不会做得太多了。如果支持的话就得要求手动修改md或者srt时如果有拆分啥的还必须强制按照顺序来，不然还可能顺序不对了；或者就是加一个命令行参数控制

**Comment by mli** [comment]
有道理。那就按照现在的，只支持merge多个视频的时候可以调顺序。cut一个视频的时候不能调。要么用视频编辑软件做，要么重新录下当前一段。

**Comment by tumuyan** [comment]
> 那就按照现在的，只支持merge多个视频的时候可以调顺序。cut一个视频的时候不能调。

那么可以考虑第三点，做一个视频cut为多个章节的功能嘛？
如果一个视频没有cut为多个章节，也就彻底无法重新排序了。

**Comment by mli** [comment]
推荐录的时候录多段。我一般一段几分钟到十来分钟。

**Comment by zealotCE** [comment]
> > 那就按照现在的，只支持merge多个视频的时候可以调顺序。cut一个视频的时候不能调。
> 
> 那么可以考虑第三点，做一个视频cut为多个章节的功能嘛？ 如果一个视频没有cut为多个章节，也就彻底无法重新排序了。

排序的话可以考虑自己来做，这块不好弄。上次沐神B站号都很明显可以看到非常容易出错的（就算你提前写好稿子，但是写好稿子的，不能完全算是autocut的目标用户了）

不过你这里其实让我想到一个 Feature ，生成支持导入视频剪辑软件的 xml。
