### ISSUE TITLE
增加cpu选项，使得显存不够也能在cpu上运行large模型，效果超级好

### ISSUE THREAD

**Issue by wk-mike** [mli/autocut#16]
为了使得小显存的电脑也能运行large模型，可以增加cpu选项，速度也不错。在cpu i5 12500   6核心12线程上运行， 1小时的视频，生成字幕也是1小时。

在`main.py`中增加
```
    parser.add_argument('--device', type=str, default='cuda',
        choices=['cpu', 'cuda'],
        help='cpu or cuda')
```
在`transcribe.py`中修改，模型导入的时候选择一下device【cpu或者cuda】
https://github.com/mli/autocut/blob/main/autocut/transcribe.py#L71
改为：
```
            self.whisper_model = whisper.load_model(self.args.whisper_model, self.args.device)
```

这样运行的时候，默认是cuda；命令增加 --device cpu 即可在cpu上运行，不用担心显存不够。

以上共大家参考。large模型效果比其他的好太多了。

**Comment by wk-mike** [comment]
李老师您好，我已经写了一个版本，如果合适可以直接接受。

pull request #17

**Comment by mli** [comment]
Merged. Also added doc in https://github.com/mli/autocut/commit/1a0ee6dc407a084f898c21414a646a2f2fdc9372
