### ISSUE TITLE
命令行运行报错

### ISSUE THREAD

**Issue by wuqile123456** [mli/autocut#2]
![Snipaste_2022-11-07_20-49-46](https://user-images.githubusercontent.com/106730009/200315687-c332c653-34d2-4f81-b819-8d3b30f0a5e2.png)
是在Windows上运行的，有兄弟也是碰到这个情况吗？？？

**Comment by wk-mike** [comment]
Linux上是正常的。你这个问题可能是后面路径中的斜线 \   要改成 双斜线 \\  ,你试试

**Comment by wuqile123456** [comment]
> 

我试过改成双斜线和反斜线，都不行，还是报同样的错。兄弟，能加你的联系方式细聊吗

**Comment by wk-mike** [comment]
我没在windows上跑过，你看看其他的issue ，好像有人在windows上跑出来了。

**Comment by wuqile123456** [comment]
> 我没在windows上跑过，你看看其他的issue ，好像有人在windows上跑出来了。

好的，谢谢你了

**Comment by Wang-Jingrun** [comment]
> ![Snipaste_2022-11-07_20-49-46](https://user-images.githubusercontent.com/106730009/200315687-c332c653-34d2-4f81-b819-8d3b30f0a5e2.png) 是在Windows上运行的，有兄弟也是碰到这个情况吗？？？

我也遇到了同样的错误，不知道你有方法解决吗？

**Comment by wuqile123456** [comment]
> > ![Snipaste_2022-11-07_20-49-46](https://user-images.githubusercontent.com/106730009/200315687-c332c653-34d2-4f81-b819-8d3b30f0a5e2.png) 是在Windows上运行的，有兄弟也是碰到这个情况吗？？？
> 
> 我也遇到了同样的错误，不知道你有方法解决吗？
我今早解决了这个问题，是你的whisper没装好，你得把whisper装一下，沐神给了链接，那个里面也有setup.py，运行一下

**Comment by Wang-Jingrun** [comment]
> > > ![Snipaste_2022-11-07_20-49-46](https://user-images.githubusercontent.com/106730009/200315687-c332c653-34d2-4f81-b819-8d3b30f0a5e2.png) 是在Windows上运行的，有兄弟也是碰到这个情况吗？？？
> > 
> > 
> > 我也遇到了同样的错误，不知道你有方法解决吗？
> > 我今早解决了这个问题，是你的whisper没装好，你得把whisper装一下，沐神给了链接，那个里面也有setup.py，运行一下

了解了，感谢！

**Comment by wuqile123456** [comment]
> 



> 



> > ![Snipaste_2022-11-07_20-49-46](https://user-images.githubusercontent.com/106730009/200315687-c332c653-34d2-4f81-b819-8d3b30f0a5e2.png) 是在Windows上运行的，有兄弟也是碰到这个情况吗？？？
> 
> 不好意思，再次打扰。我试着吧whisper卸载了，重新运行了setup.py，但还是会遇到这个情况。

因为你安装autocut的 时候，他会装一部分whisper的配置，但不完全，所以你需要再次单独运行一下whisper里的setup.py文件 python setup.py install 这样就会把缺失的包下载了。然后再去运行autocut -t xxx.mp4就可以了。我早上就是这样解决的

**Comment by mli** [comment]
这个commit可能修复了bug。如果问题还在话，请reopen issue。

**Comment by Wang-Jingrun** [comment]
> 这个commit可能修复了bug。如果问题还在话，请reopen issue。
> 
> [d5f37c3](https://github.com/mli/autocut/commit/d5f37c388165da8a95a8a8322788fda3cb318583)

感谢李沐老师！问题已经解决，可以正常运行了。
