### ISSUE TITLE
不知道为什么运行时间大大超出预期

### ISSUE THREAD

**Issue by fan123199** [mli/autocut#21]
安装后， 我选了一个很小的视频（大小13MB， 时长10s）进行测试。

```
autocut -d .\10-20\
[autocut:transcribe.py:L24] INFO   Transcribing .\10-20\10月20日.mp4
100%|████████████████████████████████████████| 461M/461M [27:26<00:00, 294kiB/s]
[autocut:warnings.py:L109] WARNING C:\f_code\pyProject\autocut\venv\lib\site-packages\whisper\transcribe.py:78: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")

[autocut:transcribe.py:L81] INFO   Done transcription in 1679.6 sec
[autocut:transcribe.py:L35] INFO   Transcribed .\10-20\10月20日.mp4 to .\10-20\10月20日.srt
[autocut:transcribe.py:L37] INFO   Saved texts to .\10-20\10月20日.md to mark sentences

```

**Comment by mli** [comment]
第一次transcribe需要下载模型。下了27分钟，包含在transribing时间里面

**Comment by sunyuzheng** [comment]
在国内下载这个模型好慢啊，一晚上也没下完。记得在python.org下载python是XXkb/s的速度，可能这个模型也是这样子。不知道有没有办法自己在别的地方去下载这个模型然后放进来

**Comment by rockbenben** [comment]
环境依赖下载时可以关掉梯子，直连速度会快很多

**Comment by sunyuzheng** [comment]
嗯试了很多东西，总结一下
- 问题还是因为ffmpeg不支持M1 GPU
- whisper下载一个small或者large model速度都还可以
- 但是small model transcribe一个视频的话速度还能接受，large就难
- large model确实比small model在精确度上有很大提升（中文）

**Comment by xihajun** [comment]
@sunyuzheng 请问一下您的意思是因为ffmpeg不支持M1 GPU，使用导致`UserWarning: FP16 is not supported on CPU; using FP32 instead`么，还是说whisper模型没有load到GPU上呢？
尝试了添加一个device `mps`, 似乎也不太行`--device {cpu,cuda,mps}`
