### ISSUE TITLE
为什么默认运行在 CPU上呢，如何开启GPU处理，处理完的结果似乎字符集不对，字幕中文部分是乱码

### ISSUE THREAD

**Issue by yishibakaien** [mli/autocut#3]
![image](https://user-images.githubusercontent.com/17696228/200331680-0ff47d9f-a2d0-4606-9b37-376ff92f6cec.png)

![image](https://user-images.githubusercontent.com/17696228/200332073-5661e3fb-b54a-4211-a14d-5d291601308b.png)

![image](https://user-images.githubusercontent.com/17696228/200332108-03658e5b-3c32-4b91-b83b-60ae9413c595.png)

**Comment by yishibakaien** [comment]
> 我在Ubuntu上运行的时候，也是默认cpu运行的。你这个字符改一下vs code 右下角 UTF-8 试试

点了，没有效果

**Comment by wuqile123456** [comment]
兄弟，你是在windows上跑的吗？

**Comment by yishibakaien** [comment]
> 兄弟，你是在windows上跑的吗？

是的

**Comment by wuqile123456** [comment]
> > 兄弟，你是在windows上跑的吗？
> 
> 是的

兄弟，能加一下我qq吗？972269148 我有点问题想问你，我在windows上跑有问题呜呜X﹏X

**Comment by yishibakaien** [comment]
> > > 兄弟，你是在windows上跑的吗？
> > 
> > 
> > 是的
> 
> 兄弟，能加一下我qq吗？972269148 我有点问题想问你，我在windows上跑有问题呜呜X﹏X


加你qq需要验证问题

**Comment by yishibakaien** [comment]
解决如何开启 GPU 加速问题 
`pip uninstall torch` 
`pip cache purge`
`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116`  将这行的 cu116 换成你自己的 cuda 适配版本，例如 cuda11.7 的就写 cuda117

参考 issue https://github.com/openai/whisper/discussions/47

沐神这个demo 好多坑啊，还差一个字符集问题未解决，我生成的 .md 和 .srt 文件都是乱码，手动改成 utf-8 后并不能运行 `autocut -c xxxxx` 的命令

**Comment by mli** [comment]
gpu主要是pytorch的事情。readme有提到，默认装的可能版本有问题。需要手动装。

utf8应该是windows上独有的，linux和macos下ok。如果能解决的话，欢迎PR

**Comment by mli** [comment]
我猜是python read/write的时候需要显示指定用 `utf-8` ?

**Comment by mli** [comment]
https://github.com/mli/autocut/pull/6 应该修正了Win下乱码问题。如果还有问题请重开这个issue。

**Comment by yishibakaien** [comment]
> #6 应该修正了Win下乱码问题。如果还有问题请重开这个issue。

谢谢沐神！已解决该问题！谢谢！^_^
