### ISSUE TITLE
有奇怪的句子被吞现象

### ISSUE THREAD

**Issue by sanbuphy** [mli/autocut#36]
我在开头尝试删除了一些字幕，然后根据删除后的字幕直接-c 裁剪得到剪切后的视频，但发现没有剪切的字幕段对应的视频段落也受到了一定的影像 ，请问能怎么避免这个问题？或者说这个问题是什么造成的呢，谢谢

**Comment by mli** [comment]
可能是有些片段别识别成没有说话？你可以看下 srt 文件里面是不是被误删的段落没有识别出句子。要么试试更大的模型，例如 `--whisper-model large`，要么加个 `--vad` 试试

**Comment by sanbuphy** [comment]
> 可能是有些片段别识别成没有说话？你可以看下 srt 文件里面是不是被误删的段落没有识别出句子。要么试试更大的模型，例如 `--whisper-model large`，要么加个 `--vad` 试试

谢谢沐导回复！我确实怀疑了是--vad的原因，之前尝试后有一定的改善但还存在小问题，我打算用大模型试一试；
也可能是因为我的录制视频帧率并不是固定的（我在导入视频剪辑器的时候识别到了是变帧率需要重新压制），这也许会造成一定的影响。

**Comment by mli** [comment]
fix了vad里面的一个bug，现在vad默认开了，可以再试一下效果。

**Comment by sanbuphy** [comment]
> fix了vad里面的一个bug，现在vad默认开了，可以再试一下效果。

感谢沐导，我试试！
