### ISSUE TITLE
README -t flag

### ISSUE THREAD

**Issue by ArmandXiao** [mli/autocut#4]
> 如果不习惯Markdown文件，你也可以直接在srt文件里删除不要的句子，在剪切时不传入md文件名即可。就是 autocut -t 22-52-00.mp4 22-52-00.srt

`autocut -t 22-52-00.mp4 22-52-00.srt`
- flag 应该改成 `-c` 吧

**Comment by mli** [comment]
fixed! https://github.com/mli/autocut/commit/bc5505ba3cda666637b959ccdaf865431a811c27
