### ISSUE TITLE
安装出现错误（Mac电脑）：subprocess-exited-with-error，exit code: 128

### ISSUE THREAD

**Issue by wisRen** [mli/autocut#40]
![image](https://user-images.githubusercontent.com/96978852/202117983-f18a9b6c-dd03-4574-8fa2-e75e980c4f86.png)
git clone --filter=blob:none --quiet https://github.com/mli/autocut.git /private/var/folders/vr/cr26bvtn2p766k8919j2hrb80000gn/T/pip-req-build-iish4v7y did not run successfully.
  │ exit code: 128
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
1. 先创建了环境conda create autocut
2. 然后使用该命令：pip install git+https://github.com/mli/autocut.git，出现上面的错误。

**Comment by Guohui-Peng** [comment]
国内网络不好的话，可能安装不成功。
一种方法就是解决网络问题。另外，你可以试试我建的CN分支：[https://github.com/Guohui-Peng/autocut/tree/CN](https://github.com/Guohui-Peng/autocut/tree/CN)。
如果用docker方式，参考readme就行。不用docker的话，进入项目目录下，然后按下面顺序执行安装。
```
pip install ./whisper/ 
pip install .
```

**Comment by wisRen** [comment]
> Guohui-Peng
感谢！
刚才先测试了这样成功了：
1. pip install git+https://github.com/openai/whisper.git；
2. pip3 install torch torchvision torchaudio
3. pip install git+https://github.com/mli/autocut.git
