### ISSUE TITLE
AttributeError: module 'whisper' has no attribute 'load_audio'

### ISSUE THREAD

**Issue by yyf17** [mli/autocut#44]
工具很不错，谢谢分享。
我在运行命令时报错
```
 autocut -t 0046_video.mp4 

```
![image](https://user-images.githubusercontent.com/34536352/202478458-d4f3853b-d7de-402d-b941-b239229523a2.png)
请教，怎么修复？

os:  debian
python: 3.10
autocut install by the following cmd:

```
python steup.py install
```

**Comment by chenqianhe** [comment]
> 工具很不错，谢谢分享。 我在运行命令时报错
> 
> ```
>  autocut -t 0046_video.mp4 
> ```
> 
> ![image](https://user-images.githubusercontent.com/34536352/202478458-d4f3853b-d7de-402d-b941-b239229523a2.png) 请教，怎么修复？
> 
> os: debian python: 3.10 autocut install by the following cmd:
> 
> ```
> python steup.py install
> ```

![image](https://user-images.githubusercontent.com/54462604/202608315-4a5982fb-4c3a-44f7-8480-cea851aecf87.png)

进这个文件看看？

**Comment by Muttermal** [comment]
hello，我也遇到了同样的问题，我的信息如下：
os: macOS
python: 3.10
autocut install by the following cmd:  python steup.py install

请问有解决办法吗？

**Comment by yihong0618** [comment]
@Muttermal 

试试 `pip install .` 可以么？

**Comment by Muttermal** [comment]
> 

感谢回复，我试了pip install，问题解决了。

**Comment by yihong0618** [comment]
> 感谢回复，我试了pip install，问题解决了。

这块文档应该可以改下，我明天提个 PR
