### ISSUE TITLE
英文视频能保留两份字幕吗？

### ISSUE THREAD

**Issue by TimeVfx** [mli/autocut#50]
英文视频能保留两份字幕吗？一份英文和中文，现在是直接翻译中文了

**Comment by chenqianhe** [comment]
分别指定lang跑两次？

**Comment by mack007liu** [comment]
同问，有中文一句，翻译英文一句的视频，使用autocut -t ，生成的md,srt文件只有中文，为什么没有英语字幕？

**Comment by mack007liu** [comment]
主要目的是想把英文的视频剪掉，保留一种语言。可以做到吗

**Comment by mack007liu** [comment]
主要目的是想把英文的视频剪掉，保留一种语言。可以做到吗

**Comment by chenqianhe** [comment]
> 同问，有中文一句，翻译英文一句的视频，使用autocut -t ，生成的md,srt文件只有中文，为什么没有英语字幕？

英文应该是被翻译成中文了吧。中文模型下转录英文确实会有问题

https://github.com/mli/autocut/issues/27

**Comment by mack007liu** [comment]
> 
会解决吗

**Comment by chenqianhe** [comment]
> > 
> 
> 会解决吗

这里 whisper 本身的特性吧。指定了语言就会输出对应语言的结果

**Comment by mack007liu** [comment]
> > > 
> > 
> > 
> > 会解决吗
> 
> 这里 whisper 本身的特性吧。指定了语言就会输出对应语言的结果
> 如果指定了中文，只生成中文，然后在只有中文的srt剪切生成的mp4,还是有中文一句英文一句，跟原始的视频是一样的
