### ISSUE TITLE
python 版本问题？

### ISSUE THREAD

**Issue by wushixian** [mli/autocut#53]
我安装时出现ERROR: Package 'autocut' requires a different Python: 3.8.13 not in '>=3.9'，但我虚拟环境中的Python的确是3.8.13，是什么问题呢？

**Comment by zeqi2000** [comment]
请问是怎么解决的呢，我也是这样

**Comment by Guohui-Peng** [comment]
可以重新创建一个python版本为3.9以上的虚拟环境，然后再安装。
