### ISSUE TITLE
剪切视频时时间过长

### ISSUE THREAD

**Issue by silverswingkiller** [mli/autocut#57]
使用环境：win10，i5 10210u +mx350
使用过程：首先使用autocut -t对视频字幕进行转录，gpu占用率90%以上，速度在预期范围内；autocut -c对视频进行剪辑时，核显和mx350占用率基本为零，cpu占用率为60%左右，跑不满。
疑问：视频剪辑的话是不是只能换一个性能很强的CPU了？

**Comment by zcf0508** [comment]
剪辑视频使用的是 ffmpeg ，不支持 GPU 加速。粗略对比了一下，默认情况下 ffmpeg 是使用了全部 CPU 的。

可以试一下我的 pr https://github.com/mli/autocut/pull/59 看下有没有提升。

**Comment by mli** [comment]
ffmpeg可以开gpu压视频，但似乎质量可能会有些问题。

**Comment by silverswingkiller** [comment]
> 剪辑视频使用的是 ffmpeg ，不支持 GPU 加速。粗略对比了一下，默认情况下 ffmpeg 是使用了全部 CPU 的。
> 
> 可以试一下我的 pr #59 看下有没有提升。

好的，我试一下，多谢了

**Comment by silverswingkiller** [comment]
> ffmpeg可以开gpu压视频，但似乎质量可能会有些问题。

我在网上也找了一些使用gpu加速的方法，但都不行，并且我发现剪切视频使用的是python环境里面imageio包下面的ffmpeg，版本是4.x，不是scoop安装的5.x的ffmpeg

**Comment by mli** [comment]
ffmpeg是手动装的。可以手动更新。导出的时候可以加ffpmeg参数
