### ISSUE TITLE
使用autocut提取字幕剪辑视频出现TypeError: silero_vad() got an unexpected keyword argument 'trust_repo'不能正常剪辑视频

### ISSUE THREAD

**Issue by ZihaoXingUP** [mli/autocut#65]
用的是autocut test目录下的测试视频，发现也无法正常剪辑视频
![image](https://user-images.githubusercontent.com/68001792/209272293-3631eace-a1fe-48ce-bbe2-4f32c37a9ddd.png)

**Comment by zcf0508** [comment]
https://github.com/pytorch/pytorch/blob/master/torch/hub.py#L487

看下是不是版本不对，`trust_repo` 是在 1.12 版本加入的
