### ISSUE TITLE
安装提示找不到合适的版本（我自己提出了一个解决方法）

### ISSUE THREAD

**Issue by sanbuphy** [mli/autocut#66]
我在WSL 22.04 上安装，使用了pip install . 但是提示如下：
```
ERROR: Could not find a version that satisfies the requirement whisper (unavailable) (from autocut) (from versions: 0.9.5, 0.9.6, 0.9.7, 0.9.8, 0.9.9, 0.9.10, 0.9.11, 0.9.12, 0.9.13, 0.9.14, 0.9.15, 0.9.16, 1.0.0, 1.0.1, 1.0.2, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.1.7, 1.1.8, 1.1.9, 1.1.10)
ERROR: No matching distribution found for whisper (unavailable)
```
看上去是安装不了whisper，但我直接在whisper官网安装 pip install -U openai-whisper  也没出现任何问题，但接着pip install . 还是提示相同的错误。
于是我把setup.py中的 whisper删去后进行了 安装，测试后发现还是可以使用的（纯cpu环境）

**Comment by jagger2048** [comment]
最近重新安装后也提示了这个错误，先试试这个方案

**Comment by sanbuphy** [comment]
> 最近重新安装后也提示了这个错误，先试试这个方案

是的，需不需要注明到readme？ 我可以提交一个PR

**Comment by chenqianhe** [comment]
https://github.com/mli/autocut/blob/f66a6c029e2f4fc68064cc6bac6b21ebb976b25c/setup.py#L9

由于之前 whisper 没有发布 py 包，因此这里的配置是从 git 下载whisper；如果现在 whisper 有 release 了，就可以把这里替换成 对应 package 名称了  `openai-whisper`

**Comment by chenqianhe** [comment]
> > 最近重新安装后也提示了这个错误，先试试这个方案
> 
> 是的，需不需要注明到readme？ 我可以提交一个PR。 呼叫老师们： @Guohui-Peng @chenqianhe

可以试着修改一下，如果测试没问题可以 pr，这样以后安装也更方便了

**Comment by sanbuphy** [comment]
> > > 最近重新安装后也提示了这个错误，先试试这个方案
> > 
> > 
> > 是的，需不需要注明到readme？ 我可以提交一个PR。 呼叫老师们： @Guohui-Peng @chenqianhe
> 
> 可以试着修改一下，如果测试没问题可以 pr，这样以后安装也更方便了

收到，让我试试看

**Comment by sanbuphy** [comment]
> > > 最近重新安装后也提示了这个错误，先试试这个方案
> > 
> > 
> > 是的，需不需要注明到readme？ 我可以提交一个PR。 呼叫老师们： @Guohui-Peng @chenqianhe
> 
> 可以试着修改一下，如果测试没问题可以 pr，这样以后安装也更方便了

您好，已经PR
