### ISSUE TITLE
苹果M1芯片安装遇到困难

### ISSUE THREAD

**Issue by LaiHaofeng** [mli/autocut#69]
根据安装步骤到了本地测试，终端输入pip install .

Processing /Users/xxxxx/autocut
  Preparing metadata (setup.py) ... done
Collecting whisper@ git+https://github.com/openai/whisper.git
  Cloning https://github.com/openai/whisper.git to /private/var/folders/by/czbk451x27x5ksmtrsrl8jzm0000gn/T/pip-install-voxu3n35/whisper_137b9cf0e94b47aa8bc1c2055b37bf9e
  Running command git clone --filter=blob:none --quiet https://github.com/openai/whisper.git /private/var/folders/by/czbk451x27x5ksmtrsrl8jzm0000gn/T/pip-install-voxu3n35/whisper_137b9cf0e94b47aa8bc1c2055b37bf9e
  Resolved https://github.com/openai/whisper.git to commit 7858aa9c08d98f75575035ecd6481f462d66ca27
  Preparing metadata (setup.py) ... done
WARNING: Generating metadata for package whisper produced metadata for project name openai-whisper. Fix your #egg=whisper fragments.
Discarding git+https://github.com/openai/whisper.git: Requested openai-whisper from git+https://github.com/openai/whisper.git (from autocut==0.0.3) has inconsistent name: expected 'whisper', but metadata has 'openai-whisper'
Collecting srt
  Using cached srt-3.5.2.tar.gz (24 kB)
  Preparing metadata (setup.py) ... done
Collecting moviepy
  Using cached moviepy-1.0.3.tar.gz (388 kB)
  Preparing metadata (setup.py) ... done
Collecting opencc-python-reimplemented
  Using cached opencc_python_reimplemented-0.1.7-py2.py3-none-any.whl (481 kB)
Collecting torchaudio
  Using cached torchaudio-0.13.1-cp310-cp310-macosx_12_0_arm64.whl (3.4 MB)
Collecting parameterized
  Using cached parameterized-0.8.1-py2.py3-none-any.whl (26 kB)
ERROR: Could not find a version that satisfies the requirement whisper (unavailable) (from autocut) (from versions: 0.9.5, 0.9.6, 0.9.7, 0.9.8, 0.9.9, 0.9.10, 0.9.11, 0.9.12, 0.9.13, 0.9.14, 0.9.15, 0.9.16, 1.0.0, 1.0.1, 1.0.2, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.1.7, 1.1.8, 1.1.9, 1.1.10)
ERROR: No matching distribution found for whisper (unavailable)

小白请教安装方法。谢谢。

**Comment by appleatiger** [comment]
该问题应是whisper更新的问题，可以修改setup.py,将requirements里面whisper的对应**行**完全修改为"openai-whisper",即可。

**Comment by LaiHaofeng** [comment]
> 该问题应是whisper更新的问题，可以修改setup.py,将requirements里面whisper的对应**行**完全修改为"openai-whisper",即可。

谢谢。用vscode 打开setup.py 后，把第9行的 whisper 改为 openai-whisper ，已经成功过了这一步。但下一步的Docker 安装又卡住了……

终端输入： git clone https://github.com/mli/autocut.git
提示： fatal: destination path 'autocut' already exists and is not an empty directory.

跳过第一步，输入： docker build -t autocut .
提示： zsh: command not found: docker

**Comment by appleatiger** [comment]
安装完毕后为什么还要git clone？这是之前的步骤，同样，你都成功生成image了，为什么还要build，你应该运行docker run命令生成docker容器了   docker run --gpus all -it --name autocut -v 本机目录:/autocut/video autocut autocut -d /autocut/video --whisper-model medium

**Comment by LaiHaofeng** [comment]
> docker run命令生成dock



> 安装完毕后为什么还要git clone？这是之前的步骤，同样，你都成功生成image了，为什么还要build，你应该运行docker run命令生成docker容器了 docker run --gpus all -it --name autocut -v 本机目录:/autocut/video autocut autocut -d /autocut/video --whisper-model medium，，然后把要处理的音视频拖入本机目录就可以了

成功安装了。测试能自动识别音视频文件和自动输出md文件，但修改完md，并选择 - [X] <-- Mark if you are done editing. ，之后终端没有任何反应，始终处在“待机”状态，没有自动输出新的文件。可能小白我还不会正确用，还是我可能遗漏了哪一步呢？

**Comment by shahryarsnite** [comment]
> 

我有同样的问题，我用的是M2的机器。请问需要docker run这一步吗？
输入： docker build -t autocut .
提示： zsh: command not found: docker
