### ISSUE TITLE
几点经验：Markdown标记可能是大写X或者小写x，对于某些视频剪辑输出会导致fps=90000

### ISSUE THREAD

**Issue by wk-mike** [mli/autocut#7]
1. 在vscode里面，如果打开了jupyter-notebook，再打开md文件，直接打钩的话，markdown中标记用的是大写X ，而不是小写x，导致后续无法运行。可以用快捷键 “alt + c” 快捷标记，这时候是小写x，没有问题。

2.  对于腾讯会议录制的视频，剪辑过程中，会出现导出时长非常长，原因是cut.py中
```
# an alterantive to birate is use crf, e.g. ffmpeg_params=['-crf', '18']
final_clip.write_videofile(output_fn, audio_codec='aac', bitrate=self.args.bitrate)
```

这个里面保存的时候，fps其实是等于90000的，可以在前面加上`print(final_clip.fps)` 来看到。

我们可以参考网页https://www.ab62.cn/article/9901.html
在前面加上

```
import cv2
source_video = cv2.VideoCapture(fns['video'])
fps = source_video.get(cv2.CAP_PROP_FPS)
print("fps=",fps)

# an alterantive to birate is use crf, e.g. ffmpeg_params=['-crf', '18']
final_clip.write_videofile(output_fn, audio_codec='aac', bitrate=self.args.bitrate,fps=fps)
logging.info(f'Saved video to {output_fn}')
```

3.  腾讯会议录制的视频，在生成字幕后，使用potplayer添加字幕播放，时间大于40分钟的部分可以看到声音和字幕不同步。猜测可能跟腾讯会议录制的方式有关，有可能是变帧率的影响。

**Comment by mli** [comment]
'X' 的问题应该在 https://github.com/mli/autocut/commit/b59db64ef0f6a6ecce444c8076739510f24fcb7b fix了

fps的问题，你能试试不用 whisper 的函数 https://github.com/mli/autocut/blob/main/autocut/transcribe.py#L29 load audio

而是跟 cut 一样，用VideoFileClip读进来，https://github.com/mli/autocut/blob/main/autocut/cut.py#L105

你可以通过 `video.fps` 得到 fps，也可以 `video.set_fps(fps)` 来设置 fps。然后拿到它的audio的numpy array版本，再去whisper做转录。

在做cut的时候，也同样`set_fps`

**Comment by wk-mike** [comment]
谢谢，问题基本解决了。腾讯会议录制的视频一般来说是正常可以剪辑的，只有我用的那个腾讯会议的视频文件稍微有点问题，不过用剪映直接原封不动的导出为mp4文件，放到autocut里面就好了，没有任何问题。【那个有问题的视频文件不论怎么设置都有些问题】。
我后续测试了不同的腾讯会议录制的视频，一般来说都是正常的。


不过需要提到的是 --vad 选项似乎会将正常说话给去掉，一段视频加上--vad 之后，生成的字幕文件只有一小段了。


还有一个小问题，GitHub上更新了autocut文件之后，但是我重新使用
`pip install git+https://github.com/mli/autocut.git` 
或
 `pip install --upgrade git+https://github.com/mli/autocut.git` 
都无法更新

我猜测有可能是autocut的版本号码没有更新，一直是
`__version__ = '0.0.1'`

**Comment by mli** [comment]
默认 vad 没开。vad 对一些视频好，但一些变差。

我update一下version
