### ISSUE TITLE
编辑md文件后无法启动自动剪辑

### ISSUE THREAD

**Issue by LaiHaofeng** [mli/autocut#71]
终端输入autocut -d 文件夹地址后，生成了autocut.md、文件名.md、文件名.srt 三个新文件。

按照教程编辑文件名.md 文件，选定需要的内容后，勾选第一行「Mark if you are done editing.」，但终端一直没有任何变化，不会按照选择自动剪辑。

查看autocut.md 文件，里面只显示音视频前2句内容，并非全部内容。

终端一直停留在以下状态：

autocut -d /Users/xxxxxx/Desktop/test
[autocut:transcribe.py:L37] INFO   Transcribing /Users/xxxxxx/Desktop/test/test1.mp3
Using cache found in /Users/xxxxx/.cache/torch/hub/snakers4_silero-vad_master
[autocut:transcribe.py:L86] INFO   Done voice activity detection in 92.0 sec
  0%|                                                    | 0/60 [00:00<?, ?it/s][autocut:warnings.py:L109] WARNING /opt/homebrew/lib/python3.10/site-packages/whisper/transcribe.py:79: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")

100%|███████████████████████████████████████████| 60/60 [03:45<00:00,  3.75s/it]
[autocut:transcribe.py:L138] INFO   Done transcription in 227.1 sec
[autocut:transcribe.py:L55] INFO   Transcribed /Users/xxxxxx/Desktop/test/test1.mp3 to /Users/xxxxxx/test/test1.srt
[autocut:transcribe.py:L57] INFO   Saved texts to /Users/xxxxxx/Desktop/test/test1.md to mark sentences

是安装哪里出了问题？还是使用方法出了问题？完全的新手小白，盼指点迷津

**Comment by chenqianhe** [comment]
还有这种问题吗，看样子就是视频都没有完成转录

**Comment by arrowing** [comment]
一样的问题，还没解决吗？

**Comment by chenqianhe** [comment]
> 一样的问题，还没解决吗？

有一些更多的信息吗？例如操作、电脑系统信息、环境信息、命令行输出信息等吗？需要能了解一下出问题时候的状况再看看是怎么回事

**Comment by arrowing** [comment]
> > 一样的问题，还没解决吗？
> 
> 有一些更多的信息吗？例如操作、电脑系统信息、环境信息、命令行输出信息等吗？需要能了解一下出问题时候的状况再看看是怎么回事

与题主发的内容与操作一样。
系统是 windows 10。
输入与输出参考：
`$ autocut -d videos
[autocut:transcribe.py:L37] INFO   Done Init model in 2.0 sec
[autocut:transcribe.py:L41] INFO   Transcribing videos\test.mp4
Using cache found in C:\Users\xxx/.cache\torch\hub\snakers4_silero-vad_master
[autocut:transcribe.py:L86] INFO   Done voice activity detection in 4.7 sec
[autocut:warnings.py:L109] WARNING C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\whisper\transcribe.py:115: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1316/1316 [00:07<00:00, 175.49frames/s]
[autocut:transcribe.py:L107] INFO   Done transcription in 7.8 sec
[autocut:transcribe.py:L52] INFO   Transcribed videos\test.mp4 to videos\test.srt
[autocut:transcribe.py:L54] INFO   Saved texts to videos\test.md to mark sentences`

**Comment by chenqianhe** [comment]
> > > 一样的问题，还没解决吗？
> > 
> > 
> > 有一些更多的信息吗？例如操作、电脑系统信息、环境信息、命令行输出信息等吗？需要能了解一下出问题时候的状况再看看是怎么回事
> 
> 与题主发的内容与操作一样。 系统是 windows 10。 输入与输出参考： `$ autocut -d videos [autocut:transcribe.py:L37] INFO Done Init model in 2.0 sec [autocut:transcribe.py:L41] INFO Transcribing videos\test.mp4 Using cache found in C:\Users\xxx/.cache\torch\hub\snakers4_silero-vad_master [autocut:transcribe.py:L86] INFO Done voice activity detection in 4.7 sec [autocut:warnings.py:L109] WARNING C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\whisper\transcribe.py:115: UserWarning: FP16 is not supported on CPU; using FP32 instead warnings.warn("FP16 is not supported on CPU; using FP32 instead")
> 
> 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1316/1316 [00:07<00:00, 175.49frames/s] [autocut:transcribe.py:L107] INFO Done transcription in 7.8 sec [autocut:transcribe.py:L52] INFO Transcribed videos\test.mp4 to videos\test.srt [autocut:transcribe.py:L54] INFO Saved texts to videos\test.md to mark sentences`

确认一下编辑后的 md 有勾选 「Mark if you are done editing.」 吗？以及 md 文件是怎么编辑的呢（直接 vscode、typora或者文本文档编辑啥的）？还有能看到 md 文件对应的编码吗

**Comment by arrowing** [comment]
> > > > 一样的问题，还没解决吗？
> > > 
> > > 
> > > 有一些更多的信息吗？例如操作、电脑系统信息、环境信息、命令行输出信息等吗？需要能了解一下出问题时候的状况再看看是怎么回事
> > 
> > 
> > 与题主发的内容与操作一样。 系统是 windows 10。 输入与输出参考： `$ autocut -d videos [autocut:transcribe.py:L37] INFO Done Init model in 2.0 sec [autocut:transcribe.py:L41] INFO Transcribing videos\test.mp4 Using cache found in C:\Users\xxx/.cache\torch\hub\snakers4_silero-vad_master [autocut:transcribe.py:L86] INFO Done voice activity detection in 4.7 sec [autocut:warnings.py:L109] WARNING C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\whisper\transcribe.py:115: UserWarning: FP16 is not supported on CPU; using FP32 instead warnings.warn("FP16 is not supported on CPU; using FP32 instead")
> > 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1316/1316 [00:07<00:00, 175.49frames/s] [autocut:transcribe.py:L107] INFO Done transcription in 7.8 sec [autocut:transcribe.py:L52] INFO Transcribed videos\test.mp4 to videos\test.srt [autocut:transcribe.py:L54] INFO Saved texts to videos\test.md to mark sentences`
> 
> 确认一下编辑后的 md 有勾选 「Mark if you are done editing.」 吗？以及 md 文件是怎么编辑的呢（直接 vscode、typora或者文本文档编辑啥的）？还有能看到 md 文件对应的编码吗

勾选后保存了，按照教程操作的。
编辑器是 vscode + typora。

**Comment by arrowing** [comment]
我找到问题了，赶明儿提个 pr 吧 :)
