### ISSUE TITLE
安装时一直因为whisper不成功

### ISSUE THREAD

**Issue by baiwei0703** [mli/autocut#72]
我已经尝试了python3.7和3.9，pytorch也试过了GPU和CPU版本。但是每次安装到whisper，总会提示如下报错：“ERROR: Could not find a version that satisfies the requirement whisper (unavailable) (from autocut) (from versions: 0.9.5, 0.9.6, 0.9.7, 0.9.8, 0.9.9, 0.9.10, 0.9.11, 0.9.12, 0.9.13, 0.9.14, 0.9.15, 0.9.16, 1.0.0, 1.0.1, 1.0.2, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.1.7, 1.1.8, 1.1.9, 1.1.10)
ERROR: No matching distribution found for whisper (unavailable)"
请问该如何处理？

**Comment by baiwei0703** [comment]
我在whisper 的项目下面提了同样的问题。按照 Kim Jong Wook `的方法得到了解决。方法就是手动通过pip install openai-whisper`  来进行安装。然后我把setup.py中的"whisper @ git+https://github.com/openai/whisper.git" 给删了。再执行 `pip install .`

**Comment by bellarpa** [comment]
我跟你遇到了一样的问题，感谢你的帖子，陆陆续续装了2周终于用上了，谢谢！
