### ISSUE TITLE
执行autocut -d  xxxx报错

### ISSUE THREAD

**Issue by nikoharo** [mli/autocut#77]
![3423423](https://user-images.githubusercontent.com/96216203/223079138-b4f27438-d047-4b7d-a34e-80b6ddcd6f44.png)
请问这种是什么问题啊
[autocut:daemon.py:L38] WARNING Failed, may be due to the video is still on recording

**Comment by nikoharo** [comment]
操作环境ubuntu20.04

**Comment by JunityZhan** [comment]
请确保ffmpeg被正确安装。
我遇到了同样的问题。
在readme里有
sudo apt update && sudo apt install ffmpeg
但是我推荐去掉前面那句话直接运行sudo apt install ffmpeg
并且我解决了

**Comment by nikoharo** [comment]
> 

ok，感谢您的帮助，我已经解决了，我去看stackoverflow上的解释，貌似在conda环境下，要用conda install -c conda-forge ffmpeg？
