### ISSUE TITLE
How to solve the '[W NNPACK.cpp:53] Could not initialize NNPACK!' under apple silicon M2 MAX chip?

### ISSUE THREAD

**Issue by shahryarsnite** [mli/autocut#78]
After trying the input `autocut -d 2023-03-06`, I received the following message:

[autocut:transcribe.py:L37] INFO   Transcribing 2023-03-06/230115.mp4
Using cache found in /Users/.cache/torch/hub/snakers4_silero-vad_master
[W NNPACK.cpp:53] Could not initialize NNPACK! Reason: Unsupported hardware.
zsh: segmentation fault  autocut -d 2023-03-06

Is the failure happening because of the M2 chip since the message mentioned _Unsupported hardware_?

Thanks!

**Comment by chenqianhe** [comment]
I tested in M2 and did not find any such errors. Perhaps more information is needed
