### ISSUE TITLE
win10系统运行时报错：AttributeError: module 'argparse' has no attribute 'BooleanOptionalAction'

### ISSUE THREAD

**Issue by ilovepaper** [mli/autocut#8]
win10系统，autocut和whisper均已完整安装，在anaconda的python38环境下运行时报错如下：

![image](https://user-images.githubusercontent.com/57012991/200631481-6b716f9d-2065-4b01-834f-b0462e65f780.png)

(python38) C:\Windows\System32\2022-11-08>autocut -t 20221108_195852.mp4
Traceback (most recent call last):
  File "D:\anacoda\envs\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\anacoda\envs\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\anacoda\envs\python38\Scripts\autocut.exe\__main__.py", line 7, in <module>
  File "D:\anacoda\envs\python38\lib\site-packages\autocut\main.py", line 17, in main
    action=argparse.BooleanOptionalAction)
AttributeError: module 'argparse' has no attribute 'BooleanOptionalAction'

求大佬指点！感激不尽~！

**Comment by mli** [comment]
需要升级到 python3.9，改了setup.py 使得强制要求 >3.9 https://github.com/mli/autocut/commit/e23208d7a1f926431c2adf2848d426ea2c83bd45

**Comment by ilovepaper** [comment]
> 需要升级到 python3.9，改了setup.py 使得强制要求 >3.9 [e23208d](https://github.com/mli/autocut/commit/e23208d7a1f926431c2adf2848d426ea2c83bd45)

感谢大佬指点！！升级到python39之后貌似应该是可以运行了，我在G盘新建了一个文件夹放了一个以“大家好”开头的MP4进去，然后在该文件夹内cmd，接着conda activate python39，运行了autocut -t 123.mp4，报错如下：
![image](https://user-images.githubusercontent.com/57012991/200752313-1bc1e9dc-c956-4082-9ca5-637c5b44fde1.png)

找不到指定的文件可能是什么原因导致的呢？谢谢大佬！

**Comment by mli** [comment]
应该是找不到 ffmpeg。参考 https://ffmpeg.org/download.html#build-windows
