### ISSUE TITLE
FR: support faster-whisper

### ISSUE THREAD

**Issue by momobobe** [mli/autocut#87]
https://github.com/guillaumekln/faster-whisper this is way faster than the original implementation. It's already done the job addressed by https://github.com/mli/autocut/issues/22#issuecomment-1333486727. Also #63 and #73 are somewhat ~~useless~~ solved with this one done @yihong0618 @zcf0508

**Comment by lewangdev** [comment]
I will take this issue.

Here is my faster-whisper colab for test: https://github.com/lewangdev/faster-whisper-youtube

**Comment by lewangdev** [comment]
whisper 和 faster-whisper 接口和依赖不同，我的实现做了以下修改，感觉不适合发 PR 了

* cpu 模式下，去掉了并发
* cuda 模式下，需要安装 cuBLAS 11.x 和 cuDNN 8.x
* 改写完之后目前 unit test 有一个失败

faster-whisper 的版本：

https://github.com/lewangdev/autocut

**Comment by lewangdev** [comment]
https://github.com/mli/autocut/pull/94
